name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t pclass-waqas .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Docker container
        run: |
          echo "Deploying Docker container..."
          docker stop pclass-waqas || true
          docker rm pclass-waqas || true
          docker run -d --name pclass-waqas -p 8080:8080 -p 8081:8081 pclass-waqas

  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Test Docker deployment
        uses: curlimages/curl@v2.0.0
        run: |
          echo "Testing if the servers are up..."
          sleep 60  # Adjust if needed
          echo "Checking Docker container status..."
          docker ps
          echo "Fetching status from http://localhost:8080"
          curl -v http://localhost:8080 || true
          echo "Fetching status from http://103.151.111.202:8080"
          '[ $(curl -s -o /dev/null -w "%{http_code}" http://103.151.111.202:8080) == "200" ]'
